apiVersion: v1
kind: ConfigMap
metadata:
  name: pet-management-config
  namespace: pet-management
data:
  NODE_ENV: production
  PORT: "3000"
  DATABASE_URL: mysql://root:password@mysql:3306/pet_management
