apiVersion: v1
kind: Service
metadata:
  name: pet-management-service
  namespace: pet-management
spec:
  selector:
    app: pet-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
